id: inera.core.template
canonical: https://fhir.inera.se/ig/template
name: IneraCoreTemplate
title: "Inera FHIR Implementation Guide Template"
description: "Mall för Ineras FHIR Implementation Guides."
status: draft
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: CC0-1.0

publisher:
  name: Inera AB
  url: https://www.inera.se

jurisdiction: urn:iso:std:iso:3166#SE "Sweden"

parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: true
  i18n-default-language: sv

pages:
  index.md:
    title: Introduktion
  workflow.md:
    title: Arbetsflöde
  logical-models.md:
    title: Logiska modeller
  mappings.md:
    title: Mappningar
  profiles.md:
    title: Profiler
  terminology.md:
    title: Terminologi
  examples.md:
    title: Exempel
  downloads.md:
    title: Nedladdningar
  version-history.md:
    title: Versionshistorik
